<a href="https://colab.research.google.com/github/2403a52026-lgtm/NLP.LabAssignments/blob/main/NLP_LAB_14_4_2403a52026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install spacy transformers torch pandas datasets
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (5.0.0)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (2.10.0+cpu)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers) (3.24.2)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (1.4.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.7.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch) (3.6.1)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch) (2025.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.22.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 91.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [2]:
# spaCy for classical NLP pipeline and NER
import spacy
from spacy import displacy

# Hugging Face for transformer-based NER
from transformers import pipeline, AutoTokenizer, AutoModelForTokenClassification

# PyTorch backend
import torch

# Data handling
import pandas as pd

In [3]:
# Load English small pretrained model
nlp = spacy.load("en_core_web_sm")

In [4]:
sentences = [
    "Apple CEO Tim Cook announced new AI features in California.",
    "Lionel Messi scored a goal for Inter Miami in New York.",
    "The Prime Minister of India Narendra Modi visited France.",
    "Microsoft acquired OpenAI in a billion-dollar deal.",
    "NASA launched the Artemis mission from Florida."
]

In [5]:
print("===== spaCy NER Results =====\n")

spacy_results = []

for sentence in sentences:
    doc = nlp(sentence)
    print(f"\nSentence: {sentence}")

    for ent in doc.ents:
        print(f"Entity: {ent.text} | Label: {ent.label_}")
        spacy_results.append([sentence, ent.text, ent.label_])

===== spaCy NER Results =====


Sentence: Apple CEO Tim Cook announced new AI features in California.
Entity: Apple | Label: ORG
Entity: Tim Cook | Label: PERSON
Entity: AI | Label: GPE
Entity: California | Label: GPE

Sentence: Lionel Messi scored a goal for Inter Miami in New York.
Entity: Lionel Messi | Label: PERSON
Entity: New York | Label: GPE

Sentence: The Prime Minister of India Narendra Modi visited France.
Entity: France | Label: GPE

Sentence: Microsoft acquired OpenAI in a billion-dollar deal.
Entity: Microsoft | Label: ORG
Entity: OpenAI | Label: ORG
Entity: billion-dollar | Label: MONEY

Sentence: NASA launched the Artemis mission from Florida.
Entity: NASA | Label: ORG
Entity: Artemis | Label: NORP
Entity: Florida | Label: GPE

In [6]:
spacy_df = pd.DataFrame(spacy_results, columns=["Sentence", "Entity", "Label"])
spacy_df

                                             Sentence          Entity   Label
0   Apple CEO Tim Cook announced new AI features i...           Apple     ORG
1   Apple CEO Tim Cook announced new AI features i...        Tim Cook  PERSON
2   Apple CEO Tim Cook announced new AI features i...              AI     GPE
3   Apple CEO Tim Cook announced new AI features i...      California     GPE
4   Lionel Messi scored a goal for Inter Miami in ...    Lionel Messi  PERSON
5   Lionel Messi scored a goal for Inter Miami in ...        New York     GPE
6   The Prime Minister of India Narendra Modi visi...          France     GPE
7   Microsoft acquired OpenAI in a billion-dollar ...       Microsoft     ORG
8   Microsoft acquired OpenAI in a billion-dollar ...          OpenAI     ORG
9   Microsoft acquired OpenAI in a billion-dollar ...  billion-dollar   MONEY
10    NASA launched the Artemis mission from Florida.            NASA     ORG
11    NASA launched the Artemis mission from Florida.         Artemis    NORP
12    NASA launched the Artemis mission from Florida.         Florida     GPE

In [7]:
displacy.render(nlp(sentences[0]), style="ent", jupyter=True)

In [8]:
model_name = "dbmdz/bert-large-cased-finetuned-conll03-english"

tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForTokenClassification.from_pretrained(model_name)

ner_pipeline = pipeline("ner", model=model, tokenizer=tokenizer)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/998 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/60.0 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.33G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

BertForTokenClassification LOAD REPORT from: dbmdz/bert-large-cased-finetuned-conll03-english
Key                      | Status     |  |
-------------------------+------------+--+-
bert.pooler.dense.weight | UNEXPECTED |  |
bert.pooler.dense.bias   | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [9]:
print("\n===== Hugging Face NER Results =====\n")

hf_results = []

for sentence in sentences:
    results = ner_pipeline(sentence)

    print(f"\nSentence: {sentence}")

    for entity in results:
        word = entity["word"]
        label = entity["entity"]
        score = round(entity["score"], 4)

        print(f"Word: {word} | Label: {label} | Confidence: {score}")

        hf_results.append([sentence, word, label, score])

===== Hugging Face NER Results =====


Sentence: Apple CEO Tim Cook announced new AI features in California.
Word: Apple | Label: I-ORG | Confidence: 0.9979000091552734
Word: Tim | Label: I-PER | Confidence: 0.9995999932289124
Word: Cook | Label: I-PER | Confidence: 0.9997000098228455
Word: California | Label: I-LOC | Confidence: 0.9997000098228455

Sentence: Lionel Messi scored a goal for Inter Miami in New York.
Word: Lionel | Label: I-PER | Confidence: 0.9991000294685364
Word: Me | Label: I-PER | Confidence: 0.9991999864578247
Word: ##ssi | Label: I-PER | Confidence: 0.9979000091552734
Word: Inter | Label: I-ORG | Confidence: 0.9994000196456909
Word: Miami | Label: I-ORG | Confidence: 0.9868999719619751
Word: New | Label: I-LOC | Confidence: 0.9994999766349792
Word: York | Label: I-LOC | Confidence: 0.9991999864578247

Sentence: The Prime Minister of India Narendra Modi visited France.
Word: India | Label: I-LOC | Confidence: 0.9983000159263611
Word: Na | Label: I-PER | Confidence: 0.9993000030517578
Word: ##ren | Label: I-PER | Confidence: 0.9959999918937683
Word: ##dra | Label: I-PER | Confidence: 0.9988999962806702
Word: Mo | Label: I-PER | Confidence: 0.9991000294685364
Word: ##di | Label: I-PER | Confidence: 0.9861999750137329
Word: France | Label: I-LOC | Confidence: 0.9998000264167786

Sentence: Microsoft acquired OpenAI in a billion-dollar deal.
Word: Microsoft | Label: I-ORG | Confidence: 0.9997000098228455
Word: Open | Label: I-ORG | Confidence: 0.9994000196456909
Word: ##A | Label: I-ORG | Confidence: 0.9983000159263611
Word: ##I | Label: I-ORG | Confidence: 0.9976999759674072

Sentence: NASA launched the Artemis mission from Florida.
Word: NASA | Label: I-ORG | Confidence: 0.9965000152587891
Word: Artemis | Label: I-MISC | Confidence: 0.9825999736785889
Word: Florida | Label: I-LOC | Confidence: 0.9993000030517578

In [10]:
cleaned_results = []

for sentence in sentences:
    results = ner_pipeline(sentence)

    current_entity = ""
    current_label = ""
    current_score = 0

    for entity in results:
        word = entity["word"]

        # Remove subword token prefix ##
        if word.startswith("##"):
            current_entity += word[2:]
        else:
            if current_entity:
                cleaned_results.append([sentence, current_entity, current_label, current_score])
            current_entity = word
            current_label = entity["entity"]
            current_score = round(entity["score"], 4)

    if current_entity:
        cleaned_results.append([sentence, current_entity, current_label, current_score])

hf_df = pd.DataFrame(cleaned_results,
                     columns=["Sentence", "Entity", "Label", "Confidence Score"])

hf_df

,Sentence,Entity,Label,Confidence Score
0,Apple CEO Tim Cook announced new AI features i...,Apple,I-ORG,0.9979
1,Apple CEO Tim Cook announced new AI features i...,Tim,I-PER,0.9996
2,Apple CEO Tim Cook announced new AI features i...,Cook,I-PER,0.9997
3,Apple CEO Tim Cook announced new AI features i...,California,I-LOC,0.9997
4,Lionel Messi scored a goal for Inter Miami in ...,Lionel,I-PER,0.9991
5,Lionel Messi scored a goal for Inter Miami in ...,Messi,I-PER,0.9992
6,Lionel Messi scored a goal for Inter Miami in ...,Inter,I-ORG,0.9994
7,Lionel Messi scored a goal for Inter Miami in ...,Miami,I-ORG,0.9869
8,Lionel Messi scored a goal for Inter Miami in ...,New,I-LOC,0.9995
9,Lionel Messi scored a goal for Inter Miami in ...,York,I-LOC,0.9992
10,The Prime Minister of India Narendra Modi visi...,India,I-LOC,0.9983
11,The Prime Minister of India Narendra Modi visi...,Narendra,I-PER,0.9993
12,The Prime Minister of India Narendra Modi visi...,Modi,I-PER,0.9991
13,The Prime Minister of India Narendra Modi visi...,France,I-LOC,0.9998
14,Microsoft acquired OpenAI in a billion-dollar ...,Microsoft,I-ORG,0.9997
15,Microsoft acquired OpenAI in a billion-dollar ...,OpenAI,I-ORG,0.9994
16,NASA launched the Artemis mission from Florida.,NASA,I-ORG,0.9965
17,NASA launched the Artemis mission from Florida.,Artemis,I-MISC,0.9826
18,NASA launched the Artemis mission from Florida.,Florida,I-LOC,0.9993